//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfariq.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db38bab79d27554b96b50aa57c010cd149Entities3 : DbContext
    {
        public db38bab79d27554b96b50aa57c010cd149Entities3()
            : base("name=db38bab79d27554b96b50aa57c010cd149Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<FeedbackCondition> FeedbackConditions { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<TrialBlock> TrialBlocks { get; set; }
        public DbSet<Trial> Trials { get; set; }
        public DbSet<Word> Words { get; set; }
    }
}
