//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfariq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.TrialBlocks = new HashSet<TrialBlock>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Completed { get; set; }
    
        public virtual FeedbackCondition FeedbackCondition { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual ICollection<TrialBlock> TrialBlocks { get; set; }
    }
}
