//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfariq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialBlock
    {
        public TrialBlock()
        {
            this.Trials = new HashSet<Trial>();
            this.FailProfiles = new HashSet<Profile>();
            this.PassProfiles = new HashSet<Profile>();
        }
    
        public int Id { get; set; }
        public int IndexInSession { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual ICollection<Trial> Trials { get; set; }
        public virtual ICollection<Profile> FailProfiles { get; set; }
        public virtual ICollection<Profile> PassProfiles { get; set; }
    }
}
