//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfariq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Latency { get; set; }
        public Nullable<int> IndexInTrialBlock { get; set; }
    
        public virtual TrialBlock TrialBlock { get; set; }
        public virtual Word Word { get; set; }
        public virtual Word Answer { get; set; }
        public virtual Word Option1 { get; set; }
        public virtual Word Option2 { get; set; }
        public virtual Word Option3 { get; set; }
    }
}
